site_name: QoolQit
repo_url: "https://github.com/pasqal-io/qoolqit"
repo_name: "QoolQit"

nav:
  - Overview: index.md

  - Get started:
      - get_started/index.md
      - Install: get_started/install.md
      - Programming a neutral atom QPU: get_started/qoolqit_model.md
      - Programming with QoolQit: get_started/programming_with_qoolqit.ipynb

  - Fundamentals:
      - fundamentals/index.md
      - Introduction: fundamentals/introduction.md

      - Problem definition and embedding:
          - fundamentals/problems/index.md
          - Graphs: fundamentals/problems/graphs.md
          - Embedding: fundamentals/problems/embedding.md
          - Available Graphs:
              - fundamentals/problems/available_graphs/index.md
              - Ring: fundamentals/problems/available_graphs/ring.md
              - Square Lattice: fundamentals/problems/available_graphs/square.md
          - Available Embedders:
              - fundamentals/problems/available_embedders/index.md
              - Spring Layout Embedder: fundamentals/problems/available_embedders/spring_layout.md
              - Matrix Embedder: fundamentals/problems/available_embedders/matrix.md
              - BlaDe: fundamentals/problems/available_embedders/blade.md

      - Quantum Program:
          - fundamentals/quantum_program/index.md
          - Registers:
              - fundamentals/quantum_program/registers/index.md
              - From Graphs: fundamentals/quantum_program/registers/from_graph.md
              - From Positions: fundamentals/quantum_program/registers/from_positions.md
              - From Embeddings: fundamentals/quantum_program/registers/from_embeddings.md
          - Drives:
              - fundamentals/quantum_program/drives/index.md
              - Waveforms: fundamentals/quantum_program/drives/waveforms.md
              - DMM: fundamentals/quantum_program/drives/dmm.md
          - Defining Programs: fundamentals/defining_programs.md

      - Compilation:
          - fundamentals/compilation/index.md
          - Rationale: fundamentals/compilation/rationale.md
          - Devices: fundamentals/compilation/devices.md
          - How to Compile: fundamentals/compilation/how_to_compile.md
          - Error handling: fundamentals/compilation/error_handling.md
          - Breaking invariance: fundamentals/compilation/breaking_invariance.md

      - Execution:
          - fundamentals/execution/index.md
          - Introduction: fundamentals/execution.md
          - Local Emulators: fundamentals/execution/local_emulators.md
          - Remote Emulators: fundamentals/execution/remote_emulators.md
          - QPU: fundamentals/execution/qpu.md

  - Extended usage:
      - extended_usage/index.md
      - Adimensionalization: extended_usage/adimensionalization.md
      - Emulation configuration: extended_usage/execution_config.md
      - Custom embedders: extended_usage/custom_embedders.md
      - Custom waveforms: extended_usage/custom_waveforms.md

  - Applications:
      - tutorials/index.md
      - Solving a QUBO: tutorials/solving_a_qubo.ipynb

  - API reference:
      - reference/index.md
      - API reference: reference/api.md

  - Contribute:
      - contribute/index.md
      - How to contribute: CONTRIBUTING.md
      - Code of conduct: CODE_OF_CONDUCT.md
      - License: LICENSE.md
      - Contributor Agreement: CONTRIBUTOR_AGREEMENT.md


theme:
  name: material
  custom_dir: docs/extras/overrides/
  logo: extras/assets/logo/qoolqit_symbol_white.svg
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.view
    - content.action.edit
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: custom
    accent: custom
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: light green
    toggle:
      icon: material/weather-night
      name: Switch to light mode

markdown_extensions:
- admonition  # for notes
- pymdownx.arithmatex: # for mathjax
    generic: true
- pymdownx.highlight:
    default_lang: python
    anchor_linenums: true
    use_pygments: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.magiclink
- pymdownx.superfences
- md_in_html

plugins:
- search
- section-index
- markdown-exec
- mkdocs-jupyter:
    include: ["./docs/tutorials/*.ipynb"] # only notebooks in tutorials
- mkdocstrings:
    handlers:
      python:
        paths: [qoolqit]
        options:
          backlinks: tree
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          filters: public
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          parameter_headings: true
          type_parameter_headings: true
          preload_modules: [qoolqit]
          relative_crossrefs: true
          scoped_crossrefs: true
          separate_signature: true
          show_bases: false
          show_inheritance_diagram: false
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_signature_type_parameters: true
          show_source: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          summary: true
          unwrap_annotated: true

# For mathjax
extra_javascript:
  - extras/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

watch:
  - qoolqit

extra:
 version:
   provider: mike

# To get nice tabs
extra_css:
- extras/css/mkdocstrings.css
- extras/css/home.css
- extras/css/colors.css
