site_name: QoolQit
repo_url: "https://github.com/pasqal-io/qoolqit"
repo_name: "QoolQit"

nav:
  - Overview: index.md
  - Get started:
    - Install: get_started/install.md
    - Programming a neutral atom QPU: get_started/rydberg_model.md
    - Adimensionalization: get_started/adimensionalization.md
    - Programming with QoolQit: tutorials/programming_with_qoolqit.ipynb
  - Fundamentals:
    - Introduction: fundamentals/introduction.md
    - Problem definition and graphs: fundamentals/graphs.md
    - Problem embedding: fundamentals/available_embedders.md
    - Writing a quantum program:
      - Registers: fundamentals/registers.md
      - Waveforms: fundamentals/waveforms.md
      - Drive Hamiltonian: fundamentals/drives.md
      - Devices: fundamentals/devices.md
      - Quantum programs: fundamentals/programs.md
      - Execution: fundamentals/execution.md
  - Extended usage:
    - Custom embedders: fundamentals/custom_embedders.md
  - Applications:
    - Solving a QUBO: tutorials/solving_a_qubo.ipynb
  - Tutorials:
      - User journey: tutorials/user_journey.ipynb
      - Defining a custom quantum program: tutorials/custom_quantum_program.ipynb
      - Rydberg blockade: tutorials/rydberg_blockade.ipynb
  - API reference: reference/api.md
  - Contribute:
    - How to contribute: CONTRIBUTING.md
    - Code of conduct: CODE_OF_CONDUCT.md
    - License: LICENSE.md
    - Contributor Agreement: CONTRIBUTOR_AGREEMENT.md


theme:
  name: material
  custom_dir: docs/extras/overrides/
  logo: extras/assets/logo/qoolqit_symbol_white.svg
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.view
    - content.action.edit
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: custom
    accent: custom
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: light green
    toggle:
      icon: material/weather-night
      name: Switch to light mode

markdown_extensions:
- admonition  # for notes
- pymdownx.arithmatex: # for mathjax
    generic: true
- pymdownx.highlight:
    default_lang: python
    anchor_linenums: true
    use_pygments: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.magiclink
- pymdownx.superfences
- md_in_html

plugins:
- search
- section-index
- markdown-exec
- mkdocs-jupyter:
    include: ["./docs/tutorials/*.ipynb"] # only notebooks in tutorials
- mkdocstrings:
    handlers:
      python:
        paths: [qoolqit]
        options:
          backlinks: tree
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          filters: public
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          parameter_headings: true
          type_parameter_headings: true
          preload_modules: [qoolqit]
          relative_crossrefs: true
          scoped_crossrefs: true
          separate_signature: true
          show_bases: false
          show_inheritance_diagram: false
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_signature_type_parameters: true
          show_source: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          summary: true
          unwrap_annotated: true

# For mathjax
extra_javascript:
  - extras/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

watch:
  - qoolqit

extra:
 version:
   provider: mike

# To get nice tabs
extra_css:
- extras/css/mkdocstrings.css
- extras/css/home.css
- extras/css/colors.css
