from __future__ import annotations

from dataclasses import dataclass

import networkx as nx
import numpy as np

from qoolqit.graphs import DataGraph

from ..base_embedder import EmbeddingConfig


@dataclass
class SpringLayoutConfig(EmbeddingConfig):
    """Configuration parameters for the spring-layout embedding."""

    iterations: int = 100
    threshold: float = 1e-4
    seed: int | None = None


def spring_layout_embedding(
    graph: DataGraph,
    iterations: int,
    threshold: float,
    seed: int | None,
) -> DataGraph:
    """Force-directed embedding, wrapping `nx.spring_layout`.

    Generates a new graph with the same nodes and edges as the original graph, but with
    node coordinates set to embed edge weights into pairwise distances as wᵢⱼ=1/rᵢⱼ^6.

    The positions are generated by `nx.spring_layout`.
    Since `nx.spring_layout` embeds edge weights as wᵢⱼ = (k/rᵢⱼ)^3, we set:
     - `k=1` and `scale=None` to disable global rescaling of positions.
     - rescale weights wᵢⱼ -> wᵢⱼ^1/2
    to achieve our target embedding wᵢⱼ=1/rᵢⱼ^6.

    Check the documentation for `nx.spring_layout` for more information about each parameter:
    https://networkx.org/documentation/stable/reference/generated/networkx.drawing.layout.spring_layout.html

    Args:
        graph: the graph to embed according to its edge weights.
        iterations: maximum number of iterations to take.
        threshold: Threshold for relative error in node position changes.
            The iteration stops if force-displacement is below this threshold.
        seed: random seed for reproducibility.

    Returns:
        DataGraph: graph with the node coordinates set according to the spring-layout embedding.
    """
    # Create a copy of the input graph to avoid modifying weights in-place
    graph_for_layout = graph.copy()
    # Modify edge weights to embed into wᵢⱼ=1/rᵢⱼ^6
    for u, v, weight in graph.edges.data("weight"):
        if weight is not None:
            graph_for_layout.edges[u, v]["weight"] = np.sqrt(weight)

    # Generate the positions using spring_layout with the modified edge weights
    positions = nx.spring_layout(
        graph_for_layout, k=1, scale=None, iterations=iterations, threshold=threshold, seed=seed
    )

    # Create a new graph with the same nodes and edges as the original
    # but with node coordinates set to be the positions generated by spring_layout
    output_graph: DataGraph = graph.copy()
    nx.set_node_attributes(output_graph, values=positions, name="pos")
    output_graph.coords = positions

    return output_graph
